# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('add_time', models.DateField()),
                ('modified_time', models.DateField(null=True)),
            ],
        ),
    ]
