# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0002_auto_20180227_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
    ]
