# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0003_auto_20180227_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
