# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonApp', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('0', '保密'), ('1', '男'), ('2', '女')], max_length=2)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('note', models.CharField(max_length=100, verbose_name='备注')),
            ],
        ),
    ]
