# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0006_auto_20180305_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mod_date',
            field=models.DateTimeField(null=True, verbose_name='最后修改日期'),
        ),
    ]
