# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0007_auto_20180305_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(0, '保密'), (1, '男'), (2, '女')], max_length=2),
        ),
    ]
