# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0023_auto_20180306_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(default='保密', max_length=50),
        ),
    ]
