# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
    ]
